#!/usr/bin/env node

import { build } from "esbuild";
import { mkdir, readFile, rm, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const outdir = resolve(root, ".client-dist");
const generatedDir = resolve(root, "src/generated");
const production = process.env.NODE_ENV === "production";

await rm(outdir, { recursive: true, force: true });
await mkdir(generatedDir, { recursive: true });

await build({
	entryPoints: [resolve(root, "src/client/main.tsx")],
	bundle: true,
	format: "esm",
	loader: {
		".svg": "dataurl",
		".ttf": "dataurl",
		".woff": "dataurl",
		".woff2": "dataurl",
	},
	logLevel: "warning",
	minify: production,
	outdir,
	platform: "browser",
	sourcemap: false,
	target: "es2022",
});

const [js, css] = await Promise.all([
	readFile(resolve(outdir, "main.js"), "utf8"),
	readFile(resolve(outdir, "main.css"), "utf8").catch((error) => {
		if (error && error.code === "ENOENT") {
			return "";
		}
		throw error;
	}),
]);

await Promise.all([
	writeFile(
		resolve(generatedDir, "client.js.txt"),
		`/* Generated by scripts/build-client.mjs. Do not edit directly. */\n${js}`,
	),
	writeFile(
		resolve(generatedDir, "client.css.txt"),
		`/* Generated by scripts/build-client.mjs. Do not edit directly. */\n${css}`,
	),
]);
